export enum ESchoolSurveyDataType{
    GENERAL_INFORMATION = 'GENERAL_INFORMATION', OPERATIONAL_MANAGEMENT = 'OPERATIONAL_MANAGEMENT', TEACHING_AND_LEARNING = 'TEACHING_AND_LEARNING', INFRASTRUCTURE_AND_ENVIRONMENT = 'INFRASTRUCTURE_AND_ENVIRONMENT', STRATEGIC_PLANNING = 'STRATEGIC_PLANNING', STAKEHOLDERS_ENGAGEMENT= 'STAKEHOLDERS_ENGAGEMENT', CONTINOUS_IMPROVEMENT = 'CONTINOUS_IMPROVEMENT'
}