export enum ESchoolSurveyDataType{
    GENERAL_INFORMATION = 'GENERAL_INFORMATION', OPERATIONAL_MANAGEMENT = 'OPERATIONAL_MANAGEMENT', LEARNING_AND_TEACHING = 'LEARNING_AND_TEACHING', INFRASTRUCTURE = 'INFRASTRUCTURE', STRATEGIC_PLANNING = 'STRATEGIC_PLANNING', STAKEHOLDERS_ENGAGEMENT= 'STAKEHOLDERS_ENGAGEMENT', CONTINOUS_IMPROVEMENT = 'CONTINOUS_IMPROVEMENT'
}